### ISSUE TITLE
include pure python modules from sd card without installing them

### ISSUE THREAD

**Issue by FTeinz** [kuri65536/python-for-android#100]
Hallo...
I only add in my case "/mnt/sdcard/com.googlecode.pythonforandroid/extras/python/site-packages" to the PYTHONPATH to import pure python modules without installing them.

It could be usefull for someone

**Comment by kuri65536** [comment]
Hi, it is a nice tip.
I also recommend unpack your favorite module to your project directory and append the path into sys.path array.

Can I close the issue?
