### ISSUE TITLE
Python won't install

### ISSUE THREAD

**Issue by charames** [kuri65536/python-for-android#101]
* What device(s) are you experiencing the problem on?
  * Samsung Galaxy S6
* What OS version are you running on the device?
  * 5.0.2
* What version of the product are you using?
  * SL4A 6.1.1
  * PythonForAndroid r?? I don't know. When launched, it checks website for updates and reports "Versions Updated"
* What steps will reproduce the problem?
  1. Install SL42A.apk
  2. Install Python apk
  3. Open Python application
  4. Click install
  5. install fails with message "Installation Failed"
* Please provide any additional information below.

**Comment by kuri65536** [comment]
Hello, thank you to try my apks.

Can you try to reinstall [newest py4a apk](https://github.com/kuri65536/python-for-android/releases/download/r25/PythonForAndroid-debug-r25.apk) ?

**Comment by charames** [comment]
Has the same result... it says:
1) checking website for updates
2) Versions updated
3) [then I click install], it says "downloading python_r25aarch64.zip".  The download window is only there for a 2nd.  It doesn't really seem like it downloaded or extracted
4) then it flashes "Installation Failed"

**Comment by kuri65536** [comment]
oh, galaxy s6 is a 64bit system. => aarch64
it isn't r25_aarch64? (missed underscore?)

I did not prepare 64bit binaries so it was a rare case at I made this project. this is first request :D
Please use linux for android and ubuntu binary at now.
It's hard to say when made binary for aarch64.

**Comment by charames** [comment]
I don't understand what you mean by "missed underscore."  The filename it is trying to download has an underscore after r25.  Do you mean it is not supposed to have an underscore?

Also, I don't know what you are suggesting when you say to use Linux for android and Ubuntu binary at now.  Are you saying I can get a python binary from another location?  If so, Where-- and how do I get the python application to install it?

**Comment by kuri65536** [comment]
thank you thats right => underscore

I just try to say my project not support aarch64.
And point out Linux on Android as another project.
Unfortunately, your phone is very new environment aarch64.

There are some projects to use python on android,
but they are little old and not have aarch64 too...(I recommend to investigate your self)

- QPython
- Kivy
- SL4A
- Linux On Android (contain large packages include python

I guess you can insall debian or ubuntu on chroot technic and get python later, but noone would try it.

**Comment by kuri65536** [comment]
I'm sorry previous post is not meaningful and I edited again.

**Comment by kuri65536** [comment]
aarch64 may be able to run arm binary. (sorry, I do not realize that)
Python installer select aarch64 python binary but fail because it is not exist.

I will fix python installer later.
If you are hurry, please install from local with [this instruction](https://github.com/kuri65536/python-for-android#local-install)

* get zips (pyrhon-r25.zip, extras, scripts) from the releases space.
* rename (append _aarch64 before .zip) to file name.
* push binaries to your phone.
* install from local by installer.

**Comment by kuri65536** [comment]
I release new version of installer: PythonForAndroid-debug-r26.apk, Could you try [the apk](https://github.com/kuri65536/python-for-android/releases/download/r26/PythonForAndroid-debug-r26.apk) again?

**Comment by charames** [comment]
Sweet! That worked.
Downloaded, installed. Ran test.py
Thanks SOOOOO much.
