### ISSUE TITLE
'Remote Control' mechanism is unclear

### ISSUE THREAD

**Issue by jayachar88** [kuri65536/python-for-android#102]
The instructions for ['Remote Control'](https://code.google.com/p/android-python27/wiki/RemoteControl), that enables developing python script for Android on PC, before using adb + port-forwarding to execute the script on Android device/emulator, don't seem to work presently.

Following the step where using adb we send an Intent to the RPC-Server, fails with following message:

> Starting: Intent { act=com.android.python27.LAUNCH_RPC_SERVER cmp=com.android.python27/.RpcServerLauncher (has extras) }
> 
> Error type 3
> Error: Activity class {com.android.python27/com.android.python27.RpcServerLauncher} does not exist.

Note that I had modified original command as follows:-
> adb shell am start -a com.googlecode.pythonforandroid.LAUNCH_RPC_SERVER -n com.googlecode.pythonforandroid/.RpcServerLauncher --ei com.googlecode.pythonforandroid.RPC_SERVER_PORT 45777

and even then I get the error that the Activity class doesn't exist. I checked the pythonforandroid Github repository and indeed, I do not find the RpcServerLauncher anywhere.

However, when I check the **devpack/android-python27** Github repository, I do find the RpcServerLauncher.java at this location:
> android-python27/apk/src/com/android/python27/RpcServerLauncher.java

So, the question is, is this "python-for-android" project *NOT SAME AS* "devpack/android-python27" project ?

**Comment by jayachar88** [comment]
Okay, I think I am overworked and confused now. I did find the following [link](https://github.com/damonkohler/sl4a/blob/wiki/RemoteControl.md) and using the procedure described there, I managed to setup *Remote-Control* that works well, although not following the procedure that I described in my issue report.

**Comment by kuri65536** [comment]
Don't mind jayachar88, I leave my desk yesterday, sorry for late reply.

* you just typo class name: com.android.python27 => com.googlecode.android_scripting.
* yes, android-python27 is not same project and I don't know well.
* Thanks to point out the [Remote Control document](https://github.com/damonkohler/sl4a/blob/wiki/RemoteControl.md), I pick this document to my repository later :D  and then will close this issue.

As you know, action or intent must be throw to SL4A, not to scripting languages.

**Comment by jayachar88** [comment]
Okay, excellent. Please note that there are several other, interesting documents in the [raw-blob Wiki in Damon Kohler's github repo](https://github.com/damonkohler/sl4a/tree/wiki), that might be missing from your repo! I've not double-checked to confirm, but I do think some are missing.

No worries about leaving desk - we must thank you for the excellent work in terms of keeping the SL4A and Py4A alive.
