### ISSUE TITLE
xmpp.py is broken

### ISSUE THREAD

**Issue by doghouselabs** [kuri65536/python-for-android#104]
please try saychat.py, you'll get an error:
AttributeError: '_ssl._SSLSocket' object has no attribute 'issuer'

after some googling, there is a problem in xmpp - this has been fixed w/ a patch linked from this thread:
https://github.com/eventlet/eventlet/issues/124

patch:
https://raw.githubusercontent.com/freebsd/freebsd-ports/master/net-im/py-xmpppy/files/patch-xmpp-transports.py

**Comment by gorrioncillo** [comment]
sorry but i have the same issue, and i wonder to know how to apply the patch?
just copy in the directory of the "saychat.py"?

**Comment by kuri65536** [comment]
Thank you for your report, doghouselabs.
I will try to patch later.

>>> gorrincillo
xmpppy/transport.py is under /mnt/sdcard/com.googlecode.pythonforandroid/extras.
please erase transport.pyc and replace it to patched transport.py.

**Comment by kuri65536** [comment]
Patch was applied to extras binary.
Sorry, I do not have a lot time this week, Please anyone try it.

**Comment by doghouselabs** [comment]
thanks Shimoda. i haven't tried your apk, i just put the patched code on my sd card and all is good.

**Comment by kuri65536** [comment]
Don't mind, doghouselabs. Thank you pointed it out.
This patch pretty simple and may work well as you tested, so I had contained it to a release binary.
Patch will apply to every new install or update.
