### ISSUE TITLE
SSL verification failed

### ISSUE THREAD

**Issue by Poeles** [kuri65536/python-for-android#106]
When using urllib2 to open any https link the following error is given:
urllib2.URLError: urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

Found a workaround by using:
import ssl
ctx = ssl._create_unverified_context()
urllib2.urlopen("https://link", context=ctx)

This works for now, but obviously a proper fix is preferred.

**Comment by kuri65536** [comment]
Thank you for your report.
I'll check it and investigate the reason of errors.

**Comment by gorrioncillo** [comment]
I'm using mechanize por check a facebook account, and i get the same.
Maybe someone know how to fix it? please

**Comment by kuri65536** [comment]
Hi, I found same issue in
* http://stackoverflow.com/questions/33140382/troubleshooting-ssl-certificate-verify-failed-error
* python 2.7.11rc1: Issue #24603: Update Windows builds and OS X 10.5 installer to use OpenSSL 1.0.2d.

I build new python-r26 binary with openssl version 1.0.2d now.
please wait for minutes.

**Comment by kuri65536** [comment]
I updated binary, but this is not solution for you.

This problem cause by lack certification files in andoird,
it is needed from python in openening sites with HTTPS.

You can set cert file via SSL_CERT_FILE environment,
and root cert file is available from curl.haxx.se/ca/cacert.pem.

In new script package, take_cacert_pem.py was bundled and it download pem file to /mnt/sdcard.
In my test script(test.py), there is sample code to set SSL_CERT_FILE like::
```python
 def test_106_https_certification_failed():      # issue #106 {{{1               
    import urllib2                                                              
    import os                                                                   
    import take_cacert_pem                                                      
    if take_cacert_pem.main():                                                  
        return False                                                            
    os.environ["SSL_CERT_FILE"] = "/mnt/sdcard/cacert.pem"                      
    # input = input.replace("!web ", "")                                        
    url = "https://ccc.de/"                                                     
    # url = "https://www.openssl.org/"                                          
    req = urllib2.Request(url)                                                  
    info = urllib2.urlopen(req).read()                                          
    info                                                                        
    return True                         
```
please set os.environ in your script before getting html which you want.

### My memorandom
* set SSL_CERT_DIR to /etc/security/cacerts is not solved this problem,
   maybe Android cert format not match to openssl-1.0.2d library.
* SSL_CERT_FILE can be set from SL4A but cacert.pem file location is not clear,
  and cert files must be newest so using system cert files may be reasonable (like CPython).
* Android cacerts/* files is valied for openssl lib, but capath or SSL_CERT_DIR is not work.
  Is there any method to pass multiple cert files to ssl.py...?

**Comment by Poeles** [comment]
Thanks for the work on this! I was able to get it to work by setting os.environ["SSL_CERT_FILE"] and using the cacert.pem from curl. However, I wanted to try to set it as an environment variable and I couldn't get that to work. I'm using Python to run scripts from another app (NZBGet), where I have defined some python variables at the daemon startup, like: 

`export PYTHONHOME=/data/data/com.googlecode.pythonforandroid/files/python`

It tried using this to set the SSL file as well but that didn't work:
`export SSL_CERT_FILE=/data/local/cacert/pem`

Any clue how I can get it to work that way, or if that is even possible?

**Comment by kuri65536** [comment]
I think your method is right, but check the typo:
```shell
export SSL_CERT_FILE=/data/local/cacert/pem
```
might be
```shell
export SSL_CERT_FILE=/data/local/cacert.pem
```

**Comment by Poeles** [comment]
What a dumb mistake, can't believe I overlooked that. That does indeed work, thanks!

**Comment by Poeles** [comment]
As there is a lack of cert files in android it might be wise to opt out of the default verification of certificates. More about this here: https://www.python.org/dev/peps/pep-0476/

You would have to patch the ssl module:
`import ssl

try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    # Legacy Python that doesn't verify HTTPS certificates by default
    pass
else:
    # Handle target environment that doesn't support HTTPS verification
    ssl._create_default_https_context = _create_unverified_https_context`

**Comment by kuri65536** [comment]
I appreciate hearing that python running, on your newer device than I have. :D

Thank you for suggestion.
And as I read from PEP, I will try to custom ssl.py for searching system cert files.

**Comment by krok55** [comment]
Hello,

I was wondering if there is any progress with this issue?
I'm still getting the above error after working with python 2.7.11 on android 5.1
I'm executing third-party scripts, so there is no way for me to use any intrusive patch.

Previously I was using the "original" sl4a libraries on android 4, everything was working fine.
Is there any solution on the way?

Thanks

**Comment by kuri65536** [comment]
please try `test_106_https_certification_failed()` in above.

**Comment by kuri65536** [comment]
It will be include next release.
