### ISSUE TITLE
Large File support

### ISSUE THREAD

**Issue by Poeles** [kuri65536/python-for-android#107]
When a file is large > 4 GB the file size starts decreasing and even becomes negative for larger files. This seems like an overflow issue, just tested this on a 6 GB file and android shell reports the correct 6GB but os.path.getsize() only reports a file size of 1.8 GB. Found some info about this [here](http://stackoverflow.com/questions/5579407/os-path-getsize-returns-negative-filesize-for-large-files-for-3gb-file-size) and [here](http://stackoverflow.com/questions/5167120/why-does-os-path-getsize-return-a-negative-number-for-a-10gb-file). 

Seems like you need to compile Python with: `CFLAGS='-D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64' OPT="-g -O2 $CFLAGS"`

(Sorry for raising all these issues, but I lack the knowledge to compile python myself and implement any of the fixes I find/suggest)

**Comment by kuri65536** [comment]
(No problems, poeles. suggestions are welcome!)

Thank you for reporting.
I will test this and included in the next release.
python 2.7.11 comes soon.

**Comment by kuri65536** [comment]
I checked the source of 2.7.11 and found _LARGEFILE64_SOURCE and FILE_OFFSET_BITS only affected to zlib.
the flag HAVE_LARGEFILE_SUPPORT maybe affect to posixmodule.c.
Now still work in progress.

BTW, I need a lightweight test case for this issue.

**Comment by Poeles** [comment]
How'd you mean a lightweight test case? Using os.path.getsize() on any sufficiently large file should tell you if the fix worked. If it's below the real size and/or even negative it failed. Can test stuff if you want but can't compile it myself.

**Comment by kuri65536** [comment]
How the best way to make large file like 4.0G and 3.99GB in python?
Is below sample the fastest way to create large file?
```python
fp = open("sample.bin", "wb")
fp.seek(4294967294L)
fp.write("1".encode("utf-8"))
fp.close()
```

**Comment by Poeles** [comment]
Not sure what is fastest, u could try this as it is very fast if it works for your OS:

http://stackoverflow.com/questions/6497722/how-to-create-a-very-large-file-cheaply-using-python-in-windows-7

**Comment by kuri65536** [comment]
@hollychen503  @Poeles 

I enabled the large file flags and re-build the binary at r28.
But I can't test it by my poor devices... (I have old phones it has 1GB storage and external is FAT)
Could you try the binaries and response the comments?
