### ISSUE TITLE
Installation  Failed

### ISSUE THREAD

**Issue by azulaa** [kuri65536/python-for-android#108]
- What device(s) are you experiencing the problem on?
  - Samsung Galaxy 10.1 (N8005)
- What OS version are you running on the device?
  - Android 4.4.2
- What version of the product are you using?
  - SL4A SL4A 6.1.1
  - PythonForAndroid r26
- What steps will reproduce the problem?
  1.Install SL42A.apk
  Install Python apk
  Open Python application
  Click install
  install fails with message "Installation Failed"
  Please provide any additional information below.
- What is the expected output%3F What do you see instead?
  - expected: Installation
  - see: Fail message "Installation failed"
- Please provide any additional information below.

**Comment by azulaa** [comment]
Any help? :(

**Comment by kuri65536** [comment]
Sorry, I don't have ideas for this issue.
please confirm one point.
Did your device have internet connections?
Because Py4a do online installation.

**Comment by azulaa** [comment]
Yes, I have internet connection. But, I having trouble when I try to install Py4a packages. It giving "Installation Failed" message. Also, when I try to install manually that packages, the download page is giving 404 error.

**Comment by kuri65536** [comment]
Please tell me the URL that cause 404 error,
I will check it.
Thank you reporting.

**Comment by picot56** [comment]
I got the same error message with my Android 6.0.1

**Comment by azulaa** [comment]
There are links below,
**  https://github.com/kuri65536/python-for-android/releases/r25/python_r25.zip
** https://github.com/kuri65536/python-for-android/releases/r25/python_extras_r25.zip
** https://github.com/kuri65536/python-for-android/releases/r25/python_scripts_r25.zip

Thank you.

**Comment by kuri65536** [comment]
These urls are wrong, please put "download" among release and r26.

https://github.com/kuri65536/python-for-android/releases/download/r26/python_extras_r26.zip

Thank you.
