### ISSUE TITLE
INFO:root:can't found the git server definition.

### ISSUE THREAD

**Issue by ReeganArockiasmy** [kuri65536/python-for-android#110]
Hi, I will build in your project i wll [get this error](https://www.dropbox.com/s/2wpn7r70dvxr4cr/session.html?dl=0) 

`:genURL
INFO:root:.hgrc not found and skip...
INFO:root:parse '/home/user/androidProj/kuri/python-for-android/.git/config'
INFO:root:can't found the git server definition.
`

**Comment by kuri65536** [comment]
I confirmed the problem.
This problem appears only in git environment.
I commit the fixed code, please try with new commit or use mercurial.
Sorry for inconvinience.

Thank you for your report.
