### ISSUE TITLE
zoom the windows

### ISSUE THREAD

**Issue by DemonXD** [kuri65536/python-for-android#115]
- What device(s) are you experiencing the problem on?
  LG G4 H818
- What OS version are you running on the device?
  Andriod 
- What version of the product are you using?
  - SL4A r6.1.1
  - PythonForAndroid r26
    My Suggestion:
    i can't zoom in or zoom out the text windows,and the words just like the ant.

**Comment by kuri65536** [comment]
Please use volume + and - button of your phone, it change the font to large or small.

Font size settings are in the SL4A's external library of terminal program (ConnectBot)
and I don't know how to fix it.
I'm sorry for inconvinience.

**Comment by kuri65536** [comment]
Moved to SL4A issue https://github.com/kuri65536/sl4a/issues/30
