### ISSUE TITLE
startSensingTimed causes error on LGG3

### ISSUE THREAD

**Issue by Thaumaturgist** [kuri65536/python-for-android#116]
This is a pretty simple script - 

```
import android
droid = android.Android()
droid.startSensingTimed(1,250)
```

It appears to be a problem with the listener with the LGE Knock-on Proximity Sensor.
using android montor, I am able to gather the following information from logcat:

03-14 15:44:30.020 31872-31872/com.googlecode.android_scripting I/Timeline: Timeline: Activity_launch_request id:com.googlecode.android_scripting time:58611171
03-14 15:44:30.183 31872-31872/com.googlecode.android_scripting I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@1fd3edc4 time:58611334
03-14 15:44:33.286 31872-31872/com.googlecode.android_scripting I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@1fd3edc4 time:58614437
03-14 15:44:54.007 31872-19270/com.googlecode.android_scripting V/sl4a.SimpleServer$ConnectionThread:100: Server thread 15359 died.
03-14 15:44:54.010 31872-1388/com.googlecode.android_scripting V/sl4a.SimpleServer$ConnectionThread:89: Server thread 15361 started.
03-14 15:45:05.634 31872-31872/com.googlecode.android_scripting I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@1fd3edc4 time:58646785
03-14 15:45:10.457 31872-1388/com.googlecode.android_scripting V/sl4a.JsonRpcServer:74: Received: {"params": [1, 250], "id": 0, "method": "startSensingTimed"}
03-14 15:45:10.483 31872-1388/com.googlecode.android_scripting D/SensorManager: found sensor: LGE Accelerometer, handle=0
03-14 15:45:10.483 31872-1388/com.googlecode.android_scripting D/SensorManager: found sensor: LGE Magnetic Field, handle=10
03-14 15:45:10.483 31872-1388/com.googlecode.android_scripting D/SensorManager: found sensor: LGE Magnetic Field Uncalibrated, handle=11
03-14 15:45:10.483 31872-1388/com.googlecode.android_scripting D/SensorManager: found sensor: LGE Gyroscope, handle=2
03-14 15:45:10.483 31872-1388/com.googlecode.android_scripting D/SensorManager: found sensor: LGE Gyroscope Uncalibrated, handle=8
03-14 15:45:10.484 31872-1388/com.googlecode.android_scripting D/SensorManager: found sensor: LGE Proximity, handle=48
03-14 15:45:10.484 31872-1388/com.googlecode.android_scripting D/SensorManager: found sensor: LGE Knock-on Proximity Sensor, handle=70
03-14 15:45:10.484 31872-1388/com.googlecode.android_scripting D/SensorManager: found sensor: LGE Virtual Proximity Sensor, handle=71
03-14 15:45:10.484 31872-1388/com.googlecode.android_scripting D/SensorManager: found sensor: LGE Light, handle=1
03-14 15:45:10.484 31872-1388/com.googlecode.android_scripting D/SensorManager: found sensor: LGE Pressure, handle=3
03-14 15:45:10.484 31872-1388/com.googlecode.android_scripting D/SensorManager: found sensor: LGE Gravity Sensor, handle=29
03-14 15:45:10.484 31872-1388/com.googlecode.android_scripting D/SensorManager: found sensor: LGE Linear Acceleration Sensor, handle=30
03-14 15:45:10.484 31872-1388/com.googlecode.android_scripting D/SensorManager: found sensor: LGE Rotation Vector Sensor, handle=36
03-14 15:45:10.485 31872-1388/com.googlecode.android_scripting D/SensorManager: found sensor: LGE Step Detector Sensor, handle=43
03-14 15:45:10.485 31872-1388/com.googlecode.android_scripting D/SensorManager: found sensor: LGE Step Counter Sensor, handle=44
03-14 15:45:10.485 31872-1388/com.googlecode.android_scripting D/SensorManager: found sensor: LGE Significant Motion Detector Sensor, handle=47
03-14 15:45:10.485 31872-1388/com.googlecode.android_scripting D/SensorManager: found sensor: LGE Game Rotation Vector Sensor, handle=50
03-14 15:45:10.485 31872-1388/com.googlecode.android_scripting D/SensorManager: found sensor: LGE GeoMagnetic Rotation Vector Sensor, handle=53
03-14 15:45:10.485 31872-1388/com.googlecode.android_scripting D/SensorManager: found sensor: LGE Orientation Sensor, handle=49
03-14 15:45:10.485 31872-1388/com.googlecode.android_scripting D/SensorManager: found sensor: LGE Tilt Detector Sensor, handle=55
03-14 15:45:10.485 31872-1388/com.googlecode.android_scripting D/SensorManager: found sensor: LGE Absolute Motion Detector Sensor, handle=33
03-14 15:45:10.486 31872-1388/com.googlecode.android_scripting D/SensorManager: found sensor: LGE Relative Motion Detector Sensor, handle=34
03-14 15:45:10.486 31872-1388/com.googlecode.android_scripting D/SensorManager: found sensor: Motion Accel, handle=46
03-14 15:45:10.499 31872-1388/com.googlecode.android_scripting I/SensorManager: registerListenerImpl() [Sensor: LGE Accelerometer, Rate: 0, SensorEventListener: com.googlecode.android_scripting.facade.SensorManagerFacade$SensorValuesCollector@72b5d51] by com.googlecode.android_scripting.facade.SensorManagerFacade.startSensingTimed():274
03-14 15:45:10.506 31872-1388/com.googlecode.android_scripting I/SensorManager: registerListenerImpl() [Sensor: LGE Magnetic Field, Rate: 0, SensorEventListener: com.googlecode.android_scripting.facade.SensorManagerFacade$SensorValuesCollector@72b5d51] by com.googlecode.android_scripting.facade.SensorManagerFacade.startSensingTimed():274
03-14 15:45:10.512 31872-1388/com.googlecode.android_scripting I/SensorManager: registerListenerImpl() [Sensor: LGE Magnetic Field Uncalibrated, Rate: 0, SensorEventListener: com.googlecode.android_scripting.facade.SensorManagerFacade$SensorValuesCollector@72b5d51] by com.googlecode.android_scripting.facade.SensorManagerFacade.startSensingTimed():274
03-14 15:45:10.515 31872-1388/com.googlecode.android_scripting I/SensorManager: registerListenerImpl() [Sensor: LGE Gyroscope, Rate: 0, SensorEventListener: com.googlecode.android_scripting.facade.SensorManagerFacade$SensorValuesCollector@72b5d51] by com.googlecode.android_scripting.facade.SensorManagerFacade.startSensingTimed():274
03-14 15:45:10.524 31872-1388/com.googlecode.android_scripting I/SensorManager: registerListenerImpl() [Sensor: LGE Gyroscope Uncalibrated, Rate: 0, SensorEventListener: com.googlecode.android_scripting.facade.SensorManagerFacade$SensorValuesCollector@72b5d51] by com.googlecode.android_scripting.facade.SensorManagerFacade.startSensingTimed():274
03-14 15:45:10.527 31872-1388/com.googlecode.android_scripting I/SensorManager: registerListenerImpl() [Sensor: LGE Proximity, Rate: 0, SensorEventListener: com.googlecode.android_scripting.facade.SensorManagerFacade$SensorValuesCollector@72b5d51] by com.googlecode.android_scripting.facade.SensorManagerFacade.startSensingTimed():274
03-14 15:45:10.537 31872-1388/com.googlecode.android_scripting I/SensorManager: registerListenerImpl() [Sensor: LGE Knock-on Proximity Sensor, Rate: 0, SensorEventListener: com.googlecode.android_scripting.facade.SensorManagerFacade$SensorValuesCollector@72b5d51] by com.googlecode.android_scripting.facade.SensorManagerFacade.startSensingTimed():274
03-14 15:45:10.538 31872-31872/com.googlecode.android_scripting E/SensorManager: Exception dispatching input event.
03-14 15:45:10.539 31872-31872/com.googlecode.android_scripting D/AndroidRuntime: Shutting down VM
03-14 15:45:10.539 31872-31872/com.googlecode.android_scripting E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                  Process: com.googlecode.android_scripting, PID: 31872
                                                                                  java.lang.RuntimeException: sensorLGE Knock-on Proximity Sensorwas not registered anymore.
                                                                                      at com.googlecode.android_scripting.facade.SensorManagerFacade$SensorValuesCollector.updateOneSensor(SensorManagerFacade.java:622)
                                                                                      at com.googlecode.android_scripting.facade.SensorManagerFacade$SensorValuesCollector.onSensorChanged(SensorManagerFacade.java:514)
                                                                                      at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:436)
                                                                                      at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                      at android.os.MessageQueue.next(MessageQueue.java:143)
                                                                                      at android.os.Looper.loop(Looper.java:122)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5297)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
03-14 15:45:10.543 31872-1388/com.googlecode.android_scripting I/SensorManager: registerListenerImpl() [Sensor: LGE Virtual Proximity Sensor, Rate: 0, SensorEventListener: com.googlecode.android_scripting.facade.SensorManagerFacade$SensorValuesCollector@72b5d51] by com.googlecode.android_scripting.facade.SensorManagerFacade.startSensingTimed():274
03-14 15:45:10.552 31872-1388/com.googlecode.android_scripting I/SensorManager: registerListenerImpl() [Sensor: LGE Light, Rate: 0, SensorEventListener: com.googlecode.android_scripting.facade.SensorManagerFacade$SensorValuesCollector@72b5d51] by com.googlecode.android_scripting.facade.SensorManagerFacade.startSensingTimed():274
03-14 15:45:10.555 31872-1388/com.googlecode.android_scripting I/SensorManager: registerListenerImpl() [Sensor: LGE Pressure, Rate: 0, SensorEventListener: com.googlecode.android_scripting.facade.SensorManagerFacade$SensorValuesCollector@72b5d51] by com.googlecode.android_scripting.facade.SensorManagerFacade.startSensingTimed():274
03-14 15:45:10.564 31872-1388/com.googlecode.android_scripting I/SensorManager: registerListenerImpl() [Sensor: LGE Gravity Sensor, Rate: 0, SensorEventListener: com.googlecode.android_scripting.facade.SensorManagerFacade$SensorValuesCollector@72b5d51] by com.googlecode.android_scripting.facade.SensorManagerFacade.startSensingTimed():274
03-14 15:45:10.568 31872-1388/com.googlecode.android_scripting I/SensorManager: registerListenerImpl() [Sensor: LGE Linear Acceleration Sensor, Rate: 0, SensorEventListener: com.googlecode.android_scripting.facade.SensorManagerFacade$SensorValuesCollector@72b5d51] by com.googlecode.android_scripting.facade.SensorManagerFacade.startSensingTimed():274
03-14 15:45:10.570 31872-1388/com.googlecode.android_scripting I/SensorManager: registerListenerImpl() [Sensor: LGE Rotation Vector Sensor, Rate: 0, SensorEventListener: com.googlecode.android_scripting.facade.SensorManagerFacade$SensorValuesCollector@72b5d51] by com.googlecode.android_scripting.facade.SensorManagerFacade.startSensingTimed():274
03-14 15:45:10.579 31872-1388/com.googlecode.android_scripting I/SensorManager: registerListenerImpl() [Sensor: LGE Step Detector Sensor, Rate: 0, SensorEventListener: com.googlecode.android_scripting.facade.SensorManagerFacade$SensorValuesCollector@72b5d51] by com.googlecode.android_scripting.facade.SensorManagerFacade.startSensingTimed():274
03-14 15:45:10.582 31872-1388/com.googlecode.android_scripting I/SensorManager: registerListenerImpl() [Sensor: LGE Step Counter Sensor, Rate: 0, SensorEventListener: com.googlecode.android_scripting.facade.SensorManagerFacade$SensorValuesCollector@72b5d51] by com.googlecode.android_scripting.facade.SensorManagerFacade.startSensingTimed():274
03-14 15:45:10.588 31872-1388/com.googlecode.android_scripting E/SensorManager: Trigger Sensors should use the requestTriggerSensor.
03-14 15:45:10.601 31872-1388/com.googlecode.android_scripting I/SensorManager: registerListenerImpl() [Sensor: LGE Game Rotation Vector Sensor, Rate: 0, SensorEventListener: com.googlecode.android_scripting.facade.SensorManagerFacade$SensorValuesCollector@72b5d51] by com.googlecode.android_scripting.facade.SensorManagerFacade.startSensingTimed():274
03-14 15:45:10.614 31872-1388/com.googlecode.android_scripting I/SensorManager: registerListenerImpl() [Sensor: LGE GeoMagnetic Rotation Vector Sensor, Rate: 0, SensorEventListener: com.googlecode.android_scripting.facade.SensorManagerFacade$SensorValuesCollector@72b5d51] by com.googlecode.android_scripting.facade.SensorManagerFacade.startSensingTimed():274
03-14 15:45:10.632 31872-1388/com.googlecode.android_scripting I/SensorManager: registerListenerImpl() [Sensor: LGE Orientation Sensor, Rate: 0, SensorEventListener: com.googlecode.android_scripting.facade.SensorManagerFacade$SensorValuesCollector@72b5d51] by com.googlecode.android_scripting.facade.SensorManagerFacade.startSensingTimed():274
03-14 15:45:10.635 31872-1388/com.googlecode.android_scripting I/SensorManager: registerListenerImpl() [Sensor: LGE Tilt Detector Sensor, Rate: 0, SensorEventListener: com.googlecode.android_scripting.facade.SensorManagerFacade$SensorValuesCollector@72b5d51] by com.googlecode.android_scripting.facade.SensorManagerFacade.startSensingTimed():274
03-14 15:45:10.650 31872-1388/com.googlecode.android_scripting I/SensorManager: registerListenerImpl() [Sensor: LGE Absolute Motion Detector Sensor, Rate: 0, SensorEventListener: com.googlecode.android_scripting.facade.SensorManagerFacade$SensorValuesCollector@72b5d51] by com.googlecode.android_scripting.facade.SensorManagerFacade.startSensingTimed():274
03-14 15:45:10.653 31872-1388/com.googlecode.android_scripting I/SensorManager: registerListenerImpl() [Sensor: LGE Relative Motion Detector Sensor, Rate: 0, SensorEventListener: com.googlecode.android_scripting.facade.SensorManagerFacade$SensorValuesCollector@72b5d51] by com.googlecode.android_scripting.facade.SensorManagerFacade.startSensingTimed():274
03-14 15:45:10.655 31872-1388/com.googlecode.android_scripting I/SensorManager: registerListenerImpl() [Sensor: Motion Accel, Rate: 0, SensorEventListener: com.googlecode.android_scripting.facade.SensorManagerFacade$SensorValuesCollector@72b5d51] by com.googlecode.android_scripting.facade.SensorManagerFacade.startSensingTimed():274
03-14 15:45:10.662 31872-1388/com.googlecode.android_scripting V/sl4a.JsonRpcServer:117: Sent: {"id":0,"result":null,"error":null}
03-14 15:45:10.688 31872-31872/? I/Process: Sending signal. PID: 31872 SIG: 9

**Comment by kuri65536** [comment]
Please tell us what version did you use?

**Comment by Thaumaturgist** [comment]
PythonForAndroid-debug-r26.apk

**Comment by kuri65536** [comment]
Thanks for information, these packages are built by me.

Proximity knock sensor is not implemented in SL4A 6.1.1.
So, your phone can not specify (1, 250) argument for startSensingTimed.
Please specify the sensor type by changing 1 to another.

This is the bug in my SensorFacade code.
I will fix the bug later.

Sorry for not helpful information.

**Comment by Thaumaturgist** [comment]
So is this really a bug in SL4A?  Do you want me to open a defect there?  I see the line in the SL4A code where it's throwing the error.  Bear with me as I'm pretty new at this (Android development), but I'm wondering how I would go about fixing it?

Thanks!

**Comment by kuri65536** [comment]
Yes, it may be SL4A bug, Thanks for kindly comment.

The exception throws in the default sensor value receiver in SensorFacadeManager.java:
```java
    default:
                // normal sensors (not detailed approach in SL4A 6.1>)
                if (this.updateOneSensor(event)) {
                    this.fUpdating = false;
                    return;
                }
```

```java
       /** <!-- {{{1 -->
         */
        private boolean updateOneSensor(SensorEvent ev) {
            // synchronized (mSensorReadings) {
                // TODO: only 1 sensor in 1 system. make it to N in 1 system.
                SensorInfo info = getInfo(ev.sensor.getType());
                if (info == null) {
                    throw new RuntimeException("sensor" + ev.sensor.getName() +
                                               "was not registered anymore.");
                }
                if (mSensorNumber == 1) {
```
The problem is info == null.
null was generated in getInfo and I don't implement the treatment for unknown sensor in it.
We want to change 2 points.

* work around: just ignore unknown sensor if info is null.
* fix: try to return the value of unknown sensor. 

I can not find the proxymity knock sensor in 
http://developer.android.com/reference/android/hardware/Sensor.html
Is it a new type of sensor? I think it cause unknown sensor problem.

Thank you.

**Comment by Thaumaturgist** [comment]
It's a sensor that some of the LG phones use for a "knock on" or "knock off" feature.  Where if the phone is off (sleeping), you can tap the screen 2 times to turn on/off the phone.  I don't think it's very new.  I think it's just a type of proximity sensor.  I'll see if I can get some time to play around with it and some android code at some point.  Again, I'm just starting to dabble in Android/Java development, but I'd like to learn more, and help out if I can.

**Comment by kuri65536** [comment]
move to SL4A issue https://github.com/kuri65536/sl4a/issues/29
