### ISSUE TITLE
Samsung Galaxy S4

### ISSUE THREAD

**Issue by surf902** [kuri65536/python-for-android#121]
- What device(s) are you experiencing the problem on?
  - ex: Nexus ???
- What OS version are you running on the device?
  - ex: Andriod ???
- What version of the product are you using?
  - SL4A r????
  - PythonForAndroid r??
- What steps will reproduce the problem?
  1. 
  2. 
  3. 
- What is the expected output? What do you see instead?
  - expected: launch ???
  - see: stop running
- Please provide any additional information below.

**Comment by kuri65536** [comment]
Thank you for information.
