### ISSUE TITLE
Import Module pyserial-master.zip

### ISSUE THREAD

**Issue by popado** [kuri65536/python-for-android#122]
What device(s) are you experiencing the problem on?
  Nexus 7
What OS version are you running on the device?
  Androd 5.1.1
What version of the product are you using?
  * SL4A r6.1
  * PythonForAndroid r2.7
What steps will reproduce the problem?
  1. Import Module
  2. Select pyserial-master.zip
  3. OK
What is the expected output? What do you see instead?
  * expected: go well
  * see: Errorjava.io.FileNotFoundException:/data/data/com.google.pythonforandroid/files/lib/python2.7/egg-info/pyserial-master.zip/files.txt: open failed: ENOENT (No such file or directory)
Thank you !

**Comment by kuri65536** [comment]
Sorry for late reply.

Now pyserial can be installed with python3 (r31) and pip_console.py3.
(But I did not test pyseiral myself)

**Comment by kuri65536** [comment]
https://github.com/kuri65536/python-for-android/releases/tag/r31
