### ISSUE TITLE
Can't install from python for Android apk

### ISSUE THREAD

**Issue by fofo1808** [kuri65536/python-for-android#124]
Hi,  I'm using your app to demo some useful things to do on python,  however,  yesterday y un installed sl4a and py4a. When  I tried to reinstall py4a and I go to the app and click on the install button,  it says install failed. Can you help me, is there another way to install the python interpreter in sl4a? 

Best
Andres

**Comment by fofo1808** [comment]
I found out that the app is trying to get x86_r28 but that file isn't in the repo,  can you relink the app to fetch x86_r27 or how to install it locally (I have .zip for x86r27

**Comment by fofo1808** [comment]
Tried to do local install,  but the error persists,  this is the folder we're I put the files

https://goo.gl/photos/c5Ex9rybLxaFkH7u5

**Comment by kuri65536** [comment]
Oh, sorry for inconvenience, I failed for upload new python_x86.zip.
And now I re-upload python_x86.zip.

Please try again.

**Comment by fofo1808** [comment]
It's working now :)  thank you!

**Comment by fofo1808** [comment]
U have Bitcoin?

**Comment by kuri65536** [comment]
No, I have not.
In this case, thank you reporting. missing _x86.zip is just mistake by me.
Don't mind.

But I create a bitcoin wallet now.
If you are feel to nice for this software, please donation to  1FTBAUaVdeGG9EPsGMD5j2SW8QHNc5HzjT .
I will pass the coins to some opensource project.
