### ISSUE TITLE
What is the best way to install an older version (r19)

### ISSUE THREAD

**Issue by mgrandau** [kuri65536/python-for-android#125]
I  see its easy to get r28 installed. But...

I tried dropping the r19 zip files dir where the extras go but it doesn't use them. Nothing happens when I hit the Local Install button.  The app I have uses create_unicode_buffer().  That was pulled in the wchar patch.

**Comment by kuri65536** [comment]
Sorry, I forgert how work local install... (I made it 2 years ago)
I will check the source, please wait.

I think just "path /sdcard" work collectry.
And recent phones have "/storage/emulated/0" or some, so recent phone may not work.

**Comment by kuri65536** [comment]
I got it.

Try to rename python_r19.zip to python_r28.zip.
python_extras_r19.zip to r28.zip.
python_scripts_r??.zip to r26.zip.

part of _r?? determined from [LATEST_VERSION](https://github.com/kuri65536/python-for-android/blob/master/python-build/LATEST_VERSION)
, LATEST_VERSION_EXTRA and LATEST_VERSION_SCRIPTS.

**Comment by mgrandau** [comment]
Thanks
