### ISSUE TITLE
How to get o set the AP_HANDSHAKE env variable?

### ISSUE THREAD

**Issue by 26darkcores** [kuri65536/python-for-android#126]
Is there a way to set the value of AP_HANDSHAKE environment variable? or how it works and if I need to do something to spawn the variable if I want to launch the server from adb shell to run python? how this variable is being set in the first place?

By piping the variables on the interpreter with os.environ to a file I get the variables I need to make it run on a separate shell but that variable is a mystery to me as it changes (obviously) every time I start the interpreter normally.

**Comment by 26darkcores** [comment]
Never mind it seems to be created upon connectivity. So no worries here! Still there should be more documentation on this part. We don't get much flexibility with the script provided here to run python without access to the android api.

First start a python interpreter. Then import the os module. 
After this just pipe the output to a file. I used the sys module:

# Import
import sys, os

# Redirect Output
sys.output = open('/sdcard/envirables.txt', 'w')
 
# List environment variables
os.environ

# Return everything to normal (print to screen)
sys.stdout = sys.__stdout__

Now you just need to open the file (/sdcard/envirables.txt) and remove the HAND_SHAKE entry.
Then edit the AP_PORT env variable with your choice.

Fire the adb console or your fav terminal emulator.
After that just import every variable manually or put them inside a shell script and call it.
To export a variable (use it either manually or inside the script):
# For example
export AP_PORT='12345'
 
# Fire the scripting layering for android server
shell am start -a com.googlecode.android_scripting.action.LAUNCH_SERVER -n com.googlecode.android_scripting/.activity.ScriptingLayerServiceLauncher --ei com.googlecode.android_scripting.extra.USE_SERVICE_PORT $PORT 

# Locate the python binary and call it
/data/data/com.googlecode.pythonforandroid/files/python/bin/python

# Here is a modified version of the script in this repo to include access to the android api directly without much hassle (python 2.7)

#! /system/bin/sh
st=`for i in /mnt/storage /mnt/sdcard /sdcard; do [ -d $i ] && echo $i && break; done`
if [ x$api != x ]; then :
elif ! type \cut > /dev/null; then api=14; else
    api=`grep build.version.sdk /system/build.prop | cut -d = -f 2`
fi

# I encountered a problem about a library missing so we just need to launch the server first and then wait a bit to stay on the safe side

export AP_PORT='8888' # SL4A Port

am start -a com.googlecode.android_scripting.action.LAUNCH_SERVER -n com.googlecode.android_scripting/.activity.ScriptingLayerServiceLauncher --ei com.googlecode.android_scripting.extra.USE_SERVICE_PORT $AP_PORT 

sleep 2

PW=`pwd`
export EXTERNAL_STORAGE=$st
export LANG=en
bin=/data/data/com.googlecode.pythonforandroid/files/python
ext=$st/com.googlecode.pythonforandroid/extras/python
PYTHONPATH=$ext
PYTHONPATH=${PYTHONPATH}:$bin/lib/python2.7/lib-dynload
export PYTHONPATH
export TEMP=$ext/tmp
export PYTHONHOME=/data/data/com.googlecode.pythonforandroid/files/python
export LD_LIBRARY_PATH=$bin/lib
export AP_HOST='127.0.0.1' 
export PATH='/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin'
export PY4A_EXTRAS='/storage/emulated/0/com.googlecode.pythonforandroid/extras/'
export PYTHON_EGG_CACHE='/data/user/0/com.googlecode.pythonforandroid/files/python/lib/python2.7/lib-dynload'

sleep 1

cd $PW
if [ $api -lt 14 ]; then
    run=/data/data/com.googlecode.android_scripting/files/run_pie
    if ! [ -x $run ]; then
        echo "need root permission to launch run_pie/python"
        ls -l "$run"
        # su -c "chmod 755 $run"    # this has failed...
        su -c "$run $bin/bin/python $*"
    else
        $run $bin/bin/python $*
    fi
else
    $bin/bin/python $*
fi

**Comment by kuri65536** [comment]
Thank you suggestion,
your point is launch SL4A server before python, right?

I think more helpful that the 'am start' and checking UDP into android.py script.

**Comment by 26darkcores** [comment]
That's correct sir. That would be much better
