### ISSUE TITLE
PY4A rejected by google play because OpenSSL

### ISSUE THREAD

**Issue by best-job** [kuri65536/python-for-android#127]
The vulnerabilities were addressed in OpenSSL 1.02f/1.01r. To confirm your OpenSSL version, you can do a grep search for:

\$ unzip -p YourApp.apk | strings | grep "OpenSSL"

please what the version openssl for python in python_extras_r28 ?

**Comment by kuri65536** [comment]
Thank you for your report.

OpenSSL still 1.0.2d by compilation problem. #109

**Comment by best-job** [comment]
What is the solution? .. my app rejected by google play :(

**Comment by kuri65536** [comment]
I try to build latest openssl and succeed it.
Please confirm the binary of r29 release, I did not test myself :D

BTW, please tell me your app, If you don't mind.

**Comment by best-job** [comment]
I have solved my problem
Thank you very much for your effort
it's a great job 👍

**Comment by kuri65536** [comment]
Can you tell me your application name?
I want to try it.
