### ISSUE TITLE
ImportError: No module named os

### ISSUE THREAD

**Issue by SynthMesc** [kuri65536/python-for-android#133]
So I just installed python-for-android on my Samsung Galaxy S3 phone (its rooted).

And after remounting /system to chmod python I came into this issue while running it:

root@d2can:/ # python
Traceback (most recent call last):
  File "/wd/Python-2.7.8/out/lib/python2.7/site.py", line 62, in <module>
ImportError: No module named os
1|root@d2can:/ #

Thanks in advance.

**Comment by kuri65536** [comment]
Why did you launch python directly?
If you want to launch python in shell,
some of environment variables will be needed to setup.

Please refer [our launch script python2.sh](https://github.com/kuri65536/python-for-android/blob/master/sl4atools/python2.sh)

**Comment by kuri65536** [comment]
no response and no reproduce issue.
