### ISSUE TITLE
install binwalk

### ISSUE THREAD

**Issue by sandibabsel** [kuri65536/python-for-android#145]
when i want install binwalk it show error

**Comment by sandibabsel** [comment]
How to solve it

**Comment by kuri65536** [comment]
Please tell your environment, command history and command logs.

I really don't know binwalk module, Does it have C module? ( or is it a pure python module? )
If it have C module, installation is little difficult.

1. install Android-NDK
2. download this repo with git.
3. build python-for-android2 or 3 you use. (make build environment for Python C module)
4. download binwalk
5. you should make some patch to binwalk for cross compile. see my (PyCrypto module)[https://github.com/kuri65536/python-for-android/tree/master/python-modules/PyCrypto]
6. build binwalk and package it.
7. push binwalk package to your device
8. set PYTHONBASE to point your local storage.
9. install a package with pip

**Comment by sandibabsel** [comment]
I'm using android jb 4.2.2 maxtron venus

**Comment by kuri65536** [comment]
Fill out below [dialog](https://github.com/kuri65536/python-for-android#please-tell-me-issues) . 

* What device(s) are you experiencing the problem on?
  * android jb 4.2.2 maxtron venus
* What OS version are you running on the device?
  * Andriod 4.2.2
* What version of the product are you using?
  * SL4A r????
  * PythonForAndroid r??
* What steps will reproduce the problem?
  1. 
  2. 
  3. 
* Provide logcat for detail.
* What is the expected output, What do you see instead?
  * expected: launch ???
  * see: stop running
* Please provide any additional information below.
