### ISSUE TITLE
python not running in techo y6

### ISSUE THREAD

**Issue by solytop10** [kuri65536/python-for-android#146]
* What device(s) are you experiencing the problem on?
  ans: techno
Android phone
* What OS version are you running on the device?
  * ex: Android ??? Android version 4.2.2
* What version of the product are you using?
  * SL4A r????
r6.2.0
  * PythonForAndroid r??
 PythonForAndroid r32
* What steps will reproduce the problem?
  1. 
while lunching python 3
  2. 
while running scripts
  3. 
while importing python-for-android-r32.zip 
* What is the expected output? What do you see instead?
blank screen prompting to exit 
  * expected: launch ???
initialization failed
  * see: stop running
* Please provide any additional information below.
while lunching python it brings up error message saying initialization failed

* What device(s) are you experiencing the problem on?
  ans: techno
* What OS version are you running on the device?
  * ex: Android ???
* What version of the product are you using?
  * SL4A r6.2????
  * PythonForAndroid r32??
* What steps will reproduce the problem?
  1. 
while lunching python 3
  2. 
while running scripts
  3. 
while importing python-for-android-r32.zip 
* What is the expected output? What do you see instead?
blank screen prompting to exit 
  * expected: launch ???
initialization failed
  * see: stop running
* Please provide any additional information below.
while lunching python it brings up error message saying initialization failed

**Comment by kuri65536** [comment]
r34 released and I tested with Android 6 phone.
Please try it.

**Comment by solytop10** [comment]
OK let me try it out
