### ISSUE TITLE
SL4A crashed on XiaoMI3 and PythonForAndroid installation failed

### ISSUE THREAD

**Issue by laiyuncong8404** [kuri65536/python-for-android#148]
* What device(s) are you experiencing the problem on?
  * XiaoMI3
* What OS version are you running on the device?
  * Andriod 4.4.4
* What version of the product are you using?
  * SL4A sl4a-r6.1.0-armv7-debug.apk/6.1.1/6.2.0
  * PythonForAndroid PythonForAndroid-debug-r25.apk/26
* What steps will reproduce the problem?
  1. open SL4 on my device
  2. open PythonForAndroid and click install button
* What is the expected output%3F What do you see instead?
  * see: SLA4 Crashed on start/ PythonForAndroid download success but toast 'installation failed'

**Comment by kuri65536** [comment]
Long time in no progress, now close this issue.
