### ISSUE TITLE
TypeError: makeFile() got an unexpected keyword argument 'encoding'

### ISSUE THREAD

**Issue by bartremans** [kuri65536/python-for-android#150]
* What device(s) are you experiencing the problem on?
  * Motorola Moto G5S
* What OS version are you running on the device?
  * Android 7.1.1
* What version of the product are you using?
  * sl4a-r6.1.1-arm-debug.apk
  * PythonForAndroid-debug-r26.apk
* What steps will reproduce the problem?
  Starting an example-script 
* What is the expected output? What do you see instead?
  * expected: launch of the script
  * see: 
will open the interpreter and give the error: 
  Traceback
  droid = android.Android()
  File "/home/shimoda/python-for-android/python-build/python_arm/python-ext/python/android.py", line 44, in __init__
TypeError: makeFile() got an unexpected keyword argument 'encoding'
* Please provide any additional information below.
Fresh install, first try with sl4a and python-for-android

**Comment by kuri65536** [comment]
Hi, @bartremans .
Thank you for the information.
android.py share with python2 and python3,
but python2 does not have encoding option for makeFile.

I will fix the issue but it take a while until next weekend, maybe.
please remove 'encoding' option to work around.

**Comment by bartremans** [comment]
Hi @kuri65536,

Thx for the feedback.
So how should I remove the encoding option?

Kind regards,

Bart

**Comment by kuri65536** [comment]
[This line](https://github.com/kuri65536/python-for-android/blob/d7d0026e3a0a98123179e0da52eb65d479f38fc8/python3-alpha/python-libs/ase/android.py#L44)

or use Python3 (I tested it with my phone).

**Comment by GorganRazvan** [comment]
Hello @kuri65536,

Please, can you provide an .apk build from the source with that [specific ](https://github.com/kuri65536/python-for-android/blob/d7d0026e3a0a98123179e0da52eb65d479f38fc8/python3-alpha/python-libs/ase/android.py#L44) line commented? It is just I have some issues setting up the whole built setup.

Thank you.

**Comment by kuri65536** [comment]
Hi @GorganRazvan ,

I updated the binary of python_extras_r33.zip in release. (android.py is not contained in apk)
you can get it from python4android installer.
please try it.

**Comment by ghost** [comment]
Thank you very much @kuri65536. It does work for me :)

**Comment by kuri65536** [comment]
@GorganRazvan  Thank you reporting (^-^
I glad to hear py4a work with you.
