### ISSUE TITLE
Json.decoder.JSONDecodeError:Expecting value: line 1 colum 1 (char 0)

### ISSUE THREAD

**Issue by gaogaoxinyu** [kuri65536/python-for-android#151]
What device(s) are you experiencing the problem on?
Xiaomi
What OS version are you running on the device?
Andriod 8.0
What version of the product are you using?
SL4A: Google code build
PY4A:  Python3ForAndroid-debug.apk (Python 3.6.4)
What steps will reproduce the problem?
open SL4 on my device
Run hello_world.py3 (Scripts: 32)
What is the expected output%3F 
Run the scripts successfully
What do you see instead?
see: Json.decoder.JSONDecodeError:Expecting value: line 1 colum 1 (char 0)

Detais as follow:
-------
Traceback (most recent call last)
    File "/storage/emulated/0/sl4a/scripts/hello_world.py3" , line 2, in <module>
       droid = android.Android()
   File "pythion3-extras/python3/android.py", line 47, in __init__
   File "pythion3-extras/python3/android.py", line 67, in rpc_call
   File "pythion3-extras/python3/android.py",line 58, in_rpc
   File "pythion3-extras/python3/json/__init__.py", line 354, in loads
   File "pythion3-extras/python3/json/decoder.py", line 339, in decode
   File "pythion3-extras/python3/json/decoder.py", line 357, in raw_decode
Json.decoder.JSONDecodeError:Expecting value: line 1 colum 1 (char 0)
--------

**Comment by kuri65536** [comment]
What is this? : `SL4A: Google code build`
Your details show us SL4A not responding.
Could you try SL4A at https://github.com/kuri65536/sl4a/releases/tag/6.1.1 ?

**Comment by gaogaoxinyu** [comment]
Hi @kuri65536 

Thank you for your explain
>What is this? : SL4A: Google code build
We had cloned the sl4a project from the google base and make apk
Project : platform/external/sl4a

How can I solve this problem?

BR
gaoagoxinyu

**Comment by gaogaoxinyu** [comment]
Hi @kuri65536

**Comment by kuri65536** [comment]
> We had cloned the sl4a project from the google base and make apk

Oh, I know this SL4A but I did not have the build environment of system app...
and I have not used it.

At this point, your error logs are seems SL4A not responding.
Please ask google SL4A authors.

Your problem may be incorrect API name among PY4A and SL4A.
you can change `makeToast` in hello_world.py3
to fit newer SL4A version. (I really dont know).

Thank you.

**Comment by gaogaoxinyu** [comment]
Hi @kuri65536 -san

Thank you for your suggestion

close this comment.

BR
gaogaoxinyu
