### ISSUE TITLE
how to find Python in adb shell ?

### ISSUE THREAD

**Issue by syberkitten** [kuri65536/python-for-android#152]
Installed both APKS (sl4a-r.....apk and PythonForAndroid...apk)

but when shelling to a device using ''adb shell''

there is no python command,
how to fix it ?

**Comment by kuri65536** [comment]
Adb's shell will search the binaries at /system/bin/ .
Android apps will not be install into /system/bin.

you can use https://github.com/kuri65536/python-for-android/tree/master/sl4atools to launch
py4a from adb.

**Comment by kuri65536** [comment]
also see: https://github.com/kuri65536/python-for-android/blob/master/docs/tips_runpythonfromshell.md
