### ISSUE TITLE
Sl4A.apk not found in dir

### ISSUE THREAD

**Issue by simonushie** [kuri65536/python-for-android#154]
Please i could not find the apk of sl4a on github website please can anyone be kind as to send it to me directly,i would be very grateful.May i mention that the apk may be on the site and maybe i didn't surf well enough to find it,this is not an allegation stating that the github website actually lacks the said resource it's just literally a cry for help

**Comment by aaaaalbert** [comment]
Perhaps the ["releases" section on the project's main GitHub page](https://github.com/kuri65536/python-for-android/releases) has what you need.

**Comment by kuri65536** [comment]
Thank you @aaaaalbert !
