### ISSUE TITLE
No SSL Support included in this Python

### ISSUE THREAD

**Issue by Usmanbanka** [kuri65536/python-for-android#159]
I am trying to write a program in python to send emails but getting the error : "No SSL Support included in this Python".

What to do now ? What is SSL ?
I am a newbie so please support me in detail.
![error_screen_shot](https://user-images.githubusercontent.com/22191444/58875852-04a47e80-86e6-11e9-8e50-596b1cc185e5.png)

**Comment by kuri65536** [comment]
Hi, here is python-for-android space.
please ask your question at the correct space.
