### ISSUE TITLE
How install SL4A on Termux? Is it possible?

### ISSUE THREAD

**Issue by js-compilatrum** [kuri65536/python-for-android#160]
I want install on Android 8.1 inside Termux on hardware: Cortex-A53, 1.5 Ghz, MediaTek MTK6739 with 3GB RAM.

How do it?

**Comment by kuri65536** [comment]
Yes, You can use termux and SL4A simultaneously.

- install SL4A
- install termux then install python on termux
- launch SL4A
- open SL4A socket from python on termux
- send to SL4A

**Comment by js-compilatrum** [comment]
> open SL4A socket from python on termux

Thank you for your response. Are you wrote about coding with Py socket library or by socket you mention something else?

**Comment by kuri65536** [comment]
please see: https://github.com/kuri65536/python-for-android/blob/master/python3-alpha/python-libs/ase/android.py

**Comment by Macromux** [comment]
> Yes, You can use termux and SL4A simultaneously.
> 
> - install SL4A
> - install termux then install python on termux
> - launch SL4A
> - open SL4A socket from python on termux
> - send to SL4A

Can you Clarify more?
