### ISSUE TITLE
Patch for /python-build/standalone_python.sh

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kuri65536/python-for-android#22]
```
added support for relative path. this patch will allow execuatable to execute 
in local directory thereby allowing relative directory referencing.
```

Original issue reported on code.google.com by `anant@anantshri.info` on 11 Aug 2011 at 6:21

Attachments:
* [standalone_python.sh.patch](https://storage.googleapis.com/google-code-attachments/python-for-android/issue-22/comment-0/standalone_python.sh.patch)

**Comment by kuri65536** [comment]
Patch merged in 151 (45c1e27379c9)
