### ISSUE TITLE
Function os.path.isfile raises exception

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kuri65536/python-for-android#29]
```
The Python documentation does not specify an exception thrown by this method, 
and if a path is non-existant or not readable then false should be returned.

Currently this method is generating OSError on Android.

```

Original issue reported on code.google.com by `eduardof...@gmail.com` on 5 Oct 2011 at 6:47

**Comment by kuri65536** [comment]
This is not re-procedure in python 2.7.9 or later.
But test code was made in test.py, [see python-build/python-script/test.py](../blob/master/python-build/python-scripts/test.py)
