### ISSUE TITLE
No ttyame() attribute in os module

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kuri65536/python-for-android#47]
```
What steps will reproduce the problem?
1. launch interactive python shell
2. import os
3. dir(os)

What is the expected output? What do you see instead?
I expected a ttyname attribute, but there's none

What version of the product are you using? On what operating system?
Python 2.6.2 (r262:71600, Mar 20 2011, 16:54:21) 
[GCC 4.4.3] on linux-armv7l

On Android

Please provide any additional information below.

It is referenced in the twisted sample via unix.py

```

Original issue reported on code.google.com by `dag...@gmail.com` on 2 May 2012 at 5:56

**Comment by kuri65536** [comment]
I investigate the code:
Andriod (bionic) does not have ttyname function, so python-for-android removed os.ttyname.
So in this situation, a possible solution is enabling ttyename and return dummy (and fixed) ttyname such as /dev/pts.
I don't know it is better or worse.
