### ISSUE TITLE
smtplib unable to start TLS (SSL problem)

### ISSUE THREAD

**Issue by my2038** [kuri65536/python-for-android#89]
* What device(s) are you experiencing the problem on?
  * LG G2
* What OS version are you running on the device?
  * 5.0.2
* What version of the product are you using?
  * SL4A r19 (with PIE)
  * PythonForAndroid r19 (with PIE)
* What steps will reproduce the problem?
  1. Use the python code below
  2. 
  3. 
* What is the expected output? What do you see instead?
  * expected: email okay
  * see: No SSL support included in this Python
* Please provide any additional information below.

<pre>
# send email function
def mail():
    import smtplib
    server = smtplib.SMTP('smtp.gmail.com', 587)
    server.starttls()
    #Next, log in to the server
    server.login("my username", "my password")
    #Send the mail
    msg = "\nHello!" # The /n separates the message from the headers
    server.sendmail("mymail@gmail.com", "mymail@gmail.com", msg)
    server.quit()
</pre>

**Comment by kuri65536** [comment]
I have confirmed this problem and fixed with replace ssl.pyc to ssl.py from normal python distribution (in my x86 PC).

I plan to re-packaging python_extra_r19.zip soon.
