### ISSUE TITLE
Not able to run youtube-dl

### ISSUE THREAD

**Issue by artsemionov** [kuri65536/python-for-android#90]
Android 4.4.2
Python 2.7.9
When I run youtube-dl I see various errors. It seems working fine with tests but its broken to run youtube-dl even without parameters. I hope you can fix it, your project is the only one that supports Android 5.0.

**Comment by kuri65536** [comment]
Thank you for your report.
Please let me know your problem with detail in next time.
(error logs are welcome.)

I confirm the error with libffi shared binary, and some binary corrupted from r19 to r21 release.
This will be fixed soon. ( but another errors is hidden of them.)

BTW, python3 is not corrupted and I try it, but youtube-dl was stopped at subprocess module.
I don't have idea how to fix it.

**Comment by kuri65536** [comment]
OK, I success to download the video with latest r22 release, please try it. :smiley: 
you must specify "--no-check-certificate" option to use it (I really don't know detail)

```shell
$ sh *2.sh /sdcard/sl4a/scripts/youtube-dl.py http://www.youtube.com/watch?v=j6ajyP5gPjE --no-check-certificate 
need root permission to launch run_pie/python
-rwxrw---- app_61   app_61      42908 2015-04-24 06:18 run_pie
[youtube] j6ajyP5gPjE: Downloading webpage
[youtube] j6ajyP5gPjE: Extracting video information
[youtube] j6ajyP5gPjE: Downloading DASH manifest
[download] Destination: Sample-j6ajyP5gPjE.mp4
[download] 100% of 11.69MiB in 00:09
```

please forget my previous post, thank you.
