### ISSUE TITLE
Cannot install interpreter, extras and scripts

### ISSUE THREAD

**Issue by gorrioncillo** [kuri65536/python-for-android#96]
* What device(s) are you experiencing the problem on?
  * sony ericcson xperia x10 mini pro
* What OS version are you running on the device?
  * android 2.1
* What version of the product are you using?
  * SL4A r6 (both versions from the link you give and for the code.google)
  * PythonForAndroid r21, r20, r19
* What steps will reproduce the problem?
  1. I correct install sl4a and PythonForAndroid
  2. when i open PythonForAndroid and try to download de interpreter, extras and scripts the apk say an error, and the interpreter=-1; extras=-1; scripts=-1
  3. I am connected over wifi and 3g
Is there a way to install de .zip manually?
* What is the expected output? What do you see instead?
  * expected: launch ???
  * see: stop running
* Please provide any additional information below.

**Comment by kuri65536** [comment]
Py4a application failed to fetch the apk information from intenet.
please try: menu >> Check version, sometimes.

At now you can not install the zips from local with py4a application.
If you are an expert to unix system, python binaries can be push to devices via adb.

the path(interpreter) is /data/data/com.googlecode.pythonforandroid/files/
the path(extras) is /sdcard/com.googlecode.pythonforandroid/extras/

Thank you for your detail report.

# Oh, xperia x10 mini pro is my favorite device... my friend used that.

**Comment by kuri65536** [comment]
Request for installing from local is duplicated with #53

**Comment by gorrioncillo** [comment]
i try a lot: menu-Check version, but doesn't work. I don't know why, in my sony ZR (android 4.4.4) works perfect.

**Comment by kuri65536** [comment]
Feel free to ask me :smile: 

[Here is the sample script to push python binaries and extras.](https://github.com/kuri65536/python-for-android/blob/master/tools/localinstall.sh)

requirements

* unzip program in andorid devices.
* need to set some environment variables to point adb binary in host, SDcard path in android device.

**Comment by gorrioncillo** [comment]
i try push the files, even just copy them but doesn't work, the version of code.google works, is r6 but python 2.6.2 and i want to try python 2.7.9
i don't know why this vertion doesn't reconize the files or download, i even reset the phone and reinstall the apk (r21).

**Comment by kuri65536** [comment]
Please check there is the file: /data/data/com.googlecode.pythonforandroid/files/python/bin/python,
which extracted from python_r2?.zip.

BTW, I try to make new method to install the python from SD card in this weekend.

**Comment by gorrioncillo** [comment]
i gonna wait for your new realese, but yes the pytho-r24.zip has the file, and i extrat them correct, copy to that folder annd even when i push the files there too. thanks for the help.

**Comment by kuri65536** [comment]
I was updated the installer to enable local install in r25 release.
But please be careful one point to run python 2.7 in old devices.

my SL4A >= r6x04 is needed to newer python2.7 for Android L compatibility.

**Comment by gorrioncillo** [comment]
it install but when i open it on sl4a (the one from code.google downloaded before it close jeje) suddenly close and process terminated. i cannot open the interpreter or the. py files.

**Comment by kuri65536** [comment]
I did not test with sl4a from code.google. it succeed to launch hello.py as included in sample.
And python 2.7 need SL4A >= r6x04 in my github repository.

**Comment by gorrioncillo** [comment]
thnaks for all the helpp but it do noot work, even whit r6x04 an r6x05 whe i try to open the interpreter from sl4a suddenly exit, and the samples do not work,too.
Maybe  is because my old cellphone.
the new local install works great!

**Comment by kuri65536** [comment]
Thank you for your effort and it is shame that python2.7 works for you...
Just for information,
My development environment is old cell phone (Galaxy Y pro 2.3.6), but it is newer than your.
