### ISSUE TITLE
Running your python in Android Terminal

### ISSUE THREAD

**Issue by FTeinz** [kuri65536/python-for-android#98]
Hallo I try to run your Py4a Build (r25) in Android (5.1.1 CM 12.1) Terminal on my Sony Xperia M.
First I have installed py4a 2.6 from Google Play Store an wanted to update to your build Python 2.7.
I have tryed to over install it with your APK but it don't work... I had to uninstall older Version of py4a Apk to install yours after thst it worked. you could write it to your install instructions. But that's not my problem. 

I started my old python in terminal with this script located in system/bin/py
Here the code
```python
export EXTERNAL_STORAGE=/mnt/sdcard
export PYTHONPATH=/mnt/sdcard/com.googlecode.pythonforandroid/extras/python:/data/data/com.googlecode.pythonforandroid/files/python/lib/python2.6/lib-dynload:/data/data/com.googlecode.pythonforandroid/files/python/lib/python2.6
export TEMP=/mnt/sdcard/com.googlecode.pythonforandroid/extras/python/tmp
export PYTHON_EGG_CACHE=$TEMP
export PYTHONHOME=/data/data/com.googlecode.pythonforandroid/files/python
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/data/data/com.googlecode.pythonforandroid/files/python/lib:/data/data/com.googlecode.pythonforandroid/files/python/lib/python2.6/lib-dynload:/mnt/sdcard/com.googlecode.pythonforandroid/extras/python
/data/data/com.googlecode.pythonforandroid/files/python/bin/python "$@"
```
 and here the output
```python
u0_a101@C1905:/ $ su
root@C1905:/ # py
Traceback (most recent call last):
  File "/home/shimoda/python-for-android.git/python-build/python_arm/python-ext/python/site.py", line 62, in <module>
  File "/home/shimoda/python-for-android.git/python-build/python_arm/python-ext/python/os.py", line 400, in <module>
  File "/home/shimoda/python-for-android.git/python-build/python_arm/python-ext/python/UserDict.py", line 83, in <module>
  File "/home/shimoda/python-for-android.git/python-build/python_arm/python-ext/python/_abcoll.py", line 11, in <module>
  File "/home/shimoda/python-for-android.git/python-build/python_arm/python-ext/python/abc.py", line 8, in <module>
  File "/home/shimoda/python-for-android.git/python-build/python_arm/python-ext/python/_weakrefset.py", line 5, in <module>
ImportError: No module named _weakref
1|root@C1905:/ #
```
How I can get it run? It seems to search for files in /home/shimoda/python-for-android.git/python-build/python_arm/python-ext/ but I have not a path like that... How I can change this!?

Thanks for your work

**Comment by kuri65536** [comment]
Thank you to try my binary :D

It seems that PYTHONPATH does not point C library correctly.
In your script, there are 2 "python2.6 directory" before lib-dynload.
please change it to python2.7 and retry again.

or can you try to run with my sample script from the terminal?

BTW, my compile directories path in error messages are come from
precompiled modules(pyc) to reduce source size.
Please don't care about it.

**Comment by FTeinz** [comment]
First thanks for your quick response!
In german we say "I have had tomatos over my eyes (;". My script work with your advicec!
I have tryed your standalone_python2.sh. But I get "no such file or directory" with the shebang #! /bin/sh without any shebang I get "Syntax error: 'fi' unexpected" at line 34.

**Comment by kuri65536** [comment]
sorry for late, I wasn't able to see your comment.

This is strange '\r' at the tail.
Is your py script file a DOS format? please try with Unix format.

**Comment by FTeinz** [comment]
Now it run. I only copy past the script through a clipboardmanager from pc to my mobile... The error with the shebang was #! /bin/sh is for my filesystem wrong. I had to use #! system/bin/sh!!!

Thanks a lot

I have some other problem but will open a nother Issue for it because it have nothing to do with this problem.

**Comment by FTeinz** [comment]
Is it possible to add kivy to your python packages?

**Comment by kuri65536** [comment]
very thank you for your report!
