### ISSUE TITLE
adding kivy

### ISSUE THREAD

**Issue by FTeinz** [kuri65536/python-for-android#99]
Hallo.
I just want to ask for kivy module. Is it possible to add this?
The installation from pip dont work.

**Comment by kuri65536** [comment]
I have not use kivy and below is expectation and include questions.

* do kivy need python C modules? python-for-android does not support it.
* I guess kivy used cross compile for android,
  python-for-android is native. this is not match environment.

I am interested in pyjnius work with py4a,
To use it, we need to prepare cross compiling pyjnius package.
But my py4a archives never success to cross compile packages...

**Comment by FTeinz** [comment]
I habe found/installed some other build of py4a "qpython" where kivy runs great. The containing modules should be pre compiled for py4a but I don't habe the knowlege to implement these into yout build. Could you help? I can send you the zipped module containing folder?!

**Comment by FTeinz** [comment]
Import from site-packages don't work with that modules!

**Comment by kuri65536** [comment]
Thanks for your support, FTeinz.
But native GUIs is not supported in this project like kivy, QT or wxWidget.
This project aims to use in SL4A environment. It is not fullset of python.

It is confusing that this project have same name with kivy.

Please use kivy environment to use kivy GUI.
I saw it is very active project.
